<#
.SYNOPSIS
Generates a summary report of incident metrics and trends

.DESCRIPTION
Provides comprehensive incident statistics including resolution times,
frequency by type and severity, and team performance metrics.
#>

[CmdletBinding()]
param()

# Load historical incident data from files (in a real implementation, this could be a database API call)
$incidentsPath = Join-Path $PSScriptRoot "..\incidents"
$incidents = Get-ChildItem -Path $incidentsPath -Filter "*.json" -ErrorAction SilentlyContinue |
    Get-Content -Raw | ConvertFrom-Json -AsHashtable

# Calculate metrics
$resolvedIncidents = $incidents | Where-Object { $_.status -in @("Resolved", "Closed") }
$activeIncidents = $incidents | Where-Object { $_.status -notin @("Resolved", "Closed") }

$avgResolutionTime = if ($resolvedIncidents.Count -gt 0) {
    ($resolvedIncidents | ForEach-Object {
        ([datetime]::Parse($_.resolvedAt) - [datetime]::Parse($_.createdAt)).TotalHours
    } | Measure-Object -Average).Average
} else { 0 }

# Generate report
"# Incident Management Summary Report"
""
"**Generated:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')"
"**Report Period:** Last 7 days"
""
"## Executive Summary"
"- **Total Incidents:** $($incidents.Count)"
"- **Active Incidents:** $($activeIncidents.Count)"
"- **Resolved Incidents:** $($resolvedIncidents.Count)"
"- **Average Resolution Time:** $([math]::Round($avgResolutionTime, 1)) hours"
""
"## Incidents by Severity"
$severityGroups = $incidents | Group-Object severity
foreach ($group in $severityGroups) {
    "- **$($group.Name):** $($group.Count) incidents"
}
""
"## Incidents by Type"
$typeGroups = $incidents | Group-Object type
foreach ($group in $typeGroups) {
    "- **$($group.Name):** $($group.Count) incidents"
}
""
"## Resolution Performance"
if ($resolvedIncidents.Count -gt 0) {
    "| Severity | Avg Resolution Time | Count |"
    "| -------- | ------------------- | ----- |"
    $severityMetrics = $resolvedIncidents | Group-Object severity | ForEach-Object {
        $avgTime = ($_.Group | ForEach-Object {
            ([datetime]::Parse($_.resolvedAt) - [datetime]::Parse($_.createdAt)).TotalHours
        } | Measure-Object -Average).Average
        "| $($_.Name) | $([math]::Round($avgTime, 1))h | $($_.Count) |"
    }
    $severityMetrics
} else {
    "No resolved incidents in the reporting period."
}
""
"## Current Active Incidents"
if ($activeIncidents.Count -gt 0) {
    "| Incident ID | Severity | Type | Age |"
    "| ----------- | -------- | ---- | --- |"
    foreach ($incident in $activeIncidents) {
        $age = (Get-Date) - [datetime]::Parse($incident.createdAt)
        "| $($incident.id) | $($incident.severity) | $($incident.type) | $([math]::Round($age.TotalHours, 1))h |"
    }
} else {
    "No active incidents - all systems operational! 🎉"
}
""
"---"
"*Report automatically generated by the Incident Management System*"